### ISSUE TITLE
User documentation error ?

### ISSUE THREAD

**Issue by stumarcus576** [ralna/RALFit#102]
In the user documentation (see the link below), shouldn't it say W_{ii} = 1/ (\sigma_i^2) instead of W_{ii} = 1/ (\sqrt \sigma_i) ?

https://ralfit.readthedocs.io/projects/Fortran/en/latest/?badge=latest

**Comment by talassio** [comment]
Lines of interest regarding the handling of W_{ii}: https://github.com/ralna/RALFit/blob/415d945c9173f0cdb5a192662ed41e6dbbfa9612/libRALFit/src/ral_nlls_internal.f90#L303-L321
