### ISSUE TITLE
User C and Python documentation error

### ISSUE THREAD

**Issue by stumarcus576** [ralna/RALFit#104]
In the C and Python user documentation (see the links below), it should say W_{ii} = 1/ (\sigma_i^2) instead of W_{ii} = 1/ (\sqrt \sigma_i).

https://ralfit.readthedocs.io/projects/C/en/latest/?badge=latest
https://ralfit.readthedocs.io/projects/Python/en/latest/?badge=latest

**Comment by tyronerees** [comment]
Thanks for flagging this.  The same markdown is used to generate the text in all three versions, so there seems to be an issue with the readthedocs not syncing properly -- I'll take a look.

**Comment by tyronerees** [comment]
Read the docs wasn't syncing with changes to master -- this is now fixed.
