### ISSUE TITLE
singular values

### ISSUE THREAD

**Issue by tyronerees** [ralna/RALFit#17]
The svd is computed, but is never used except to print to the screen.  Is this still needed?  If not, remove.

Return status (`svdstatus`) from `get_svd_j` is not checked.
There is no logic to handle `svdstatus/=0`.

Is it possible to remove altogether this routine and associated code?

Remove `w%smallest_sv` `%largest_sv` as well as
`inform%smallest_sv` `%largest_sv`

**Comment by tyronerees** [comment]
I've looked at the code, and I'm pretty sure this can be removed -- I've done this locally without any adverse affects on the test deck.  I think I'll keep this local for now, though (until PR #18 is merged into master) as it will only take five minutes to do, but will probably create a mess of merge conflicts that will be horrible to resolve.

**Comment by talassio** [comment]
Sounds good! we can merge it after PR#18.

cheers,

AM Sajo Castelli, PhD
Centro de Estadística y Matemática Aplicada
Universidad Simón Bolívar
Caracas - Venezuela
