### ISSUE TITLE
Python tests

### ISSUE THREAD

**Issue by tyronerees** [ralna/RALFit#30]
The test deck doesn't currently check the python interface.  Add this so that if the python script breaks, it breaks the CI build.

**Comment by talassio** [comment]
Hi Tyrone, can you please also address issue with Python 3.x C interface:
- https://github.com/ralna/RALFit/pull/18#issuecomment-482078019
I have added some changes to my pull request but can't check CI,
- https://github.com/talassio/RALFit/commit/046c28bd859f7d7505cb88f5acee1db88f0e6bdf#commitcomment-33157683
