### ISSUE TITLE
Handle correctly recovery in TR loop

### ISSUE THREAD

**Issue by talassio** [ralna/RALFit#37]
In TR loop, return `status /= 0` from `eval_r` and `eval_j` (`eval_Hf`?) should trigger recovery and not exit with `NLLS_ERROR_EVALUATION`

tl;dr `status` and `NaN` in return arrays should always trigger recovery whenever possible.

**Comment by tyronerees** [comment]
Also, there is no recovery (or any error handling) at all for the `eval_HP` call.
